[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  config-server-one/0 [idle] active: 
  mongos/0 [idle] error: hook failed: "cluster-relation-changed"
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  mongos/0 [idle] error: hook failed: "cluster-relation-changed"
[32mINFO    [0m pytest_operator.plugin:plugin.py:903 Model status:

Model  Controller           Cloud/Region         Version  SLA          Timestamp
test   localhost-localhost  localhost/localhost  3.5.3    unsupported  02:36:42Z

App                Version  Status  Scale  Charm        Channel  Rev  Exposed  Message
application                 active      1  application             0  no       
config-server-one           active      1  mongodb                 0  no       
mongos                      error       1  mongos       6/edge     3  no       hook failed: "cluster-relation-changed"
shard-one                   active      1  mongodb                 1  no       

Unit                  Workload  Agent  Machine  Public address  Ports            Message
application/0*        active    idle   2        10.159.4.247                     
  mongos/0*           error     idle            10.159.4.247                     hook failed: "cluster-relation-changed"
config-server-one/0*  active    idle   0        10.159.4.89     27017-27018/tcp  Primary
shard-one/0*          active    idle   1        10.159.4.44     27017/tcp        Primary

Machine  State    Address       Inst id        Base          AZ  Message
0        started  10.159.4.89   juju-9f93d6-0  ubuntu@22.04      Running
1        started  10.159.4.44   juju-9f93d6-1  ubuntu@22.04      Running
2        started  10.159.4.247  juju-9f93d6-2  ubuntu@22.04      Running

[32mINFO    [0m pytest_operator.plugin:plugin.py:909 Juju error logs:

machine-0: 02:26:39 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 02:26:39 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-config-server-one-0: 02:26:40 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-2: 02:27:29 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 02:27:29 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-application-0: 02:27:29 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-config-server-one-0: 02:28:32 ERROR unit.config-server-one/0.juju-log _on_secret_remove: Secret secret:crp27ehueah21tsvc4t0 seems to have no observers, could be removed
machine-1: 02:29:04 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 02:29:04 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-shard-one-0: 02:29:04 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-shard-one-0: 02:31:01 ERROR unit.shard-one/0.juju-log _on_secret_remove: Secret secret:crp28k1ueah21tsvc4tg seems to have no observers, could be removed
unit-mongos-0: 02:31:27 ERROR juju.worker.meterstatus error running "meter-status-changed": exit status 127
unit-shard-one-0: 02:31:43 ERROR unit.shard-one/0.juju-log _on_secret_remove: Secret secret:crp28k1ueah21tsvc4tg seems to have no observers, could be removed
unit-shard-one-0: 02:31:44 ERROR unit.shard-one/0.juju-log _on_secret_remove: Secret secret:crp28k1ueah21tsvc4tg seems to have no observers, could be removed
unit-shard-one-0: 02:31:51 ERROR unit.shard-one/0.juju-log _on_secret_remove: Secret secret:crp28k1ueah21tsvc4tg seems to have no observers, could be removed
unit-shard-one-0: 02:31:56 ERROR unit.shard-one/0.juju-log _on_secret_remove: Secret secret:crp28k1ueah21tsvc4tg seems to have no observers, could be removed
unit-mongos-0: 02:33:53 ERROR unit.mongos/0.juju-log An exception occurred when installing charmed-mongodb. Reason: Snap: 'charmed-mongodb'; command ['snap', 'install', 'charmed-mongodb', '--channel="6/edge"', '--revision="87"'] failed with output = ''
unit-shard-one-0: 02:34:16 ERROR unit.shard-one/0.juju-log Charm is in sharding role: database. Does not support shard interface.
unit-mongos-0: 02:34:52 ERROR unit.mongos/0.juju-log cluster:7: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mongos-0/charm/./src/charm.py", line 430, in <module>
    ops.main(MongosOperatorCharm)
  File "/var/lib/juju/agents/unit-mongos-0/charm/venv/ops/main.py", line 451, in __call__
    return main(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-mongos-0/charm/venv/ops/main.py", line 436, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mongos-0/charm/venv/ops/main.py", line 144, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mongos-0/charm/venv/ops/framework.py", line 351, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mongos-0/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mongos-0/charm/venv/ops/framework.py", line 942, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mongos-0/charm/lib/charms/mongodb/v0/config_server_interface.py", line 225, in _on_relation_changed
    self.charm.restart_mongos_service()
  File "/var/lib/juju/agents/unit-mongos-0/charm/./src/charm.py", line 231, in restart_mongos_service
    self.stop_mongos_service()
  File "/var/lib/juju/agents/unit-mongos-0/charm/./src/charm.py", line 222, in stop_mongos_service
    mongodb_snap = snap_cache["charmed-mongodb"]
  File "/var/lib/juju/agents/unit-mongos-0/charm/lib/charms/operator_libs_linux/v1/snap.py", line 795, in __getitem__
    self._snap_map[snap_name] = self._load_info(snap_name)
  File "/var/lib/juju/agents/unit-mongos-0/charm/lib/charms/operator_libs_linux/v1/snap.py", line 843, in _load_info
    info = self._snap_client.get_snap_information(name)
  File "/var/lib/juju/agents/unit-mongos-0/charm/lib/charms/operator_libs_linux/v1/snap.py", line 751, in get_snap_information
    return self._request("GET", "find", {"name": name})[0]
  File "/var/lib/juju/agents/unit-mongos-0/charm/lib/charms/operator_libs_linux/v1/snap.py", line 708, in _request
    response = self._request_raw(method, path, query, headers, data)
  File "/var/lib/juju/agents/unit-mongos-0/charm/lib/charms/operator_libs_linux/v1/snap.py", line 729, in _request_raw
    response = self.opener.open(request, timeout=self.timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/var/lib/juju/agents/unit-mongos-0/charm/lib/charms/operator_libs_linux/v1/snap.py", line 645, in http_open
    return self.do_open(_UnixSocketConnection, req, socket_path=self.socket_path)
  File "/usr/lib/python3.10/urllib/request.py", line 1352, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
TimeoutError: timed out
unit-mongos-0: 02:34:52 ERROR juju.worker.uniter.operation hook "cluster-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-mongos-0: 02:34:58 ERROR unit.mongos/0.juju-log cluster:7: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mongos-0/charm/lib/charms/operator_libs_linux/v1/snap.py", line 309, in _snap_daemons
    return subprocess.run(_cmd, universal_newlines=True, check=True, capture_output=True)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['snap', 'stop', 'charmed-mongodb.mongos']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mongos-0/charm/./src/charm.py", line 430, in <module>
    ops.main(MongosOperatorCharm)
  File "/var/lib/juju/agents/unit-mongos-0/charm/venv/ops/main.py", line 451, in __call__
    return main(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-mongos-0/charm/venv/ops/main.py", line 434, in main
    framework.reemit()
  File "/var/lib/juju/agents/unit-mongos-0/charm/venv/ops/framework.py", line 863, in reemit
    self._reemit()
  File "/var/lib/juju/agents/unit-mongos-0/charm/venv/ops/framework.py", line 942, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mongos-0/charm/lib/charms/mongodb/v0/config_server_interface.py", line 225, in _on_relation_changed
    self.charm.restart_mongos_service()
  File "/var/lib/juju/agents/unit-mongos-0/charm/./src/charm.py", line 231, in restart_mongos_service
    self.stop_mongos_service()
  File "/var/lib/juju/agents/unit-mongos-0/charm/./src/charm.py", line 223, in stop_mongos_service
    mongodb_snap.stop(services=["mongos"])
  File "/var/lib/juju/agents/unit-mongos-0/charm/lib/charms/operator_libs_linux/v1/snap.py", line 357, in stop
    self._snap_daemons(args, services)
  File "/var/lib/juju/agents/unit-mongos-0/charm/lib/charms/operator_libs_linux/v1/snap.py", line 311, in _snap_daemons
    raise SnapError("Could not {} for snap [{}]: {}".format(_cmd, self._name, e.stderr))
charms.operator_libs_linux.v1.snap.SnapError: Could not ['snap', 'stop', 'charmed-mongodb.mongos'] for snap [charmed-mongodb]: error: snap "charmed-mongodb" has no service "mongos"

unit-mongos-0: 02:34:58 ERROR juju.worker.uniter.operation hook "cluster-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-mongos-0: 02:35:10 ERROR unit.mongos/0.juju-log cluster:7: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mongos-0/charm/lib/charms/operator_libs_linux/v1/snap.py", line 309, in _snap_daemons
    return subprocess.run(_cmd, universal_newlines=True, check=True, capture_output=True)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['snap', 'stop', 'charmed-mongodb.mongos']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mongos-0/charm/./src/charm.py", line 430, in <module>
    ops.main(MongosOperatorCharm)
  File "/var/lib/juju/agents/unit-mongos-0/charm/venv/ops/main.py", line 451, in __call__
    return main(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-mongos-0/charm/venv/ops/main.py", line 434, in main
    framework.reemit()
  File "/var/lib/juju/agents/unit-mongos-0/charm/venv/ops/framework.py", line 863, in reemit
    self._reemit()
  File "/var/lib/juju/agents/unit-mongos-0/charm/venv/ops/framework.py", line 942, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mongos-0/charm/lib/charms/mongodb/v0/config_server_interface.py", line 225, in _on_relation_changed
    self.charm.restart_mongos_service()
  File "/var/lib/juju/agents/unit-mongos-0/charm/./src/charm.py", line 231, in restart_mongos_service
    self.stop_mongos_service()
  File "/var/lib/juju/agents/unit-mongos-0/charm/./src/charm.py", line 223, in stop_mongos_service
    mongodb_snap.stop(services=["mongos"])
  File "/var/lib/juju/agents/unit-mongos-0/charm/lib/charms/operator_libs_linux/v1/snap.py", line 357, in stop
    self._snap_daemons(args, services)
  File "/var/lib/juju/agents/unit-mongos-0/charm/lib/charms/operator_libs_linux/v1/snap.py", line 311, in _snap_daemons
    raise SnapError("Could not {} for snap [{}]: {}".format(_cmd, self._name, e.stderr))
charms.operator_libs_linux.v1.snap.SnapError: Could not ['snap', 'stop', 'charmed-mongodb.mongos'] for snap [charmed-mongodb]: error: snap "charmed-mongodb" has no service "mongos"

unit-mongos-0: 02:35:10 ERROR juju.worker.uniter.operation hook "cluster-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-mongos-0: 02:35:35 ERROR unit.mongos/0.juju-log cluster:7: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mongos-0/charm/./src/charm.py", line 430, in <module>
    ops.main(MongosOperatorCharm)
  File "/var/lib/juju/agents/unit-mongos-0/charm/venv/ops/main.py", line 451, in __call__
    return main(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-mongos-0/charm/venv/ops/main.py", line 434, in main
    framework.reemit()
  File "/var/lib/juju/agents/unit-mongos-0/charm/venv/ops/framework.py", line 863, in reemit
    self._reemit()
  File "/var/lib/juju/agents/unit-mongos-0/charm/venv/ops/framework.py", line 942, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mongos-0/charm/lib/charms/mongodb/v0/config_server_interface.py", line 225, in _on_relation_changed
    self.charm.restart_mongos_service()
  File "/var/lib/juju/agents/unit-mongos-0/charm/./src/charm.py", line 231, in restart_mongos_service
    self.stop_mongos_service()
  File "/var/lib/juju/agents/unit-mongos-0/charm/./src/charm.py", line 222, in stop_mongos_service
    mongodb_snap = snap_cache["charmed-mongodb"]
  File "/var/lib/juju/agents/unit-mongos-0/charm/lib/charms/operator_libs_linux/v1/snap.py", line 795, in __getitem__
    self._snap_map[snap_name] = self._load_info(snap_name)
  File "/var/lib/juju/agents/unit-mongos-0/charm/lib/charms/operator_libs_linux/v1/snap.py", line 843, in _load_info
    info = self._snap_client.get_snap_information(name)
  File "/var/lib/juju/agents/unit-mongos-0/charm/lib/charms/operator_libs_linux/v1/snap.py", line 751, in get_snap_information
    return self._request("GET", "find", {"name": name})[0]
  File "/var/lib/juju/agents/unit-mongos-0/charm/lib/charms/operator_libs_linux/v1/snap.py", line 708, in _request
    response = self._request_raw(method, path, query, headers, data)
  File "/var/lib/juju/agents/unit-mongos-0/charm/lib/charms/operator_libs_linux/v1/snap.py", line 729, in _request_raw
    response = self.opener.open(request, timeout=self.timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/var/lib/juju/agents/unit-mongos-0/charm/lib/charms/operator_libs_linux/v1/snap.py", line 645, in http_open
    return self.do_open(_UnixSocketConnection, req, socket_path=self.socket_path)
  File "/usr/lib/python3.10/urllib/request.py", line 1352, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
TimeoutError: timed out
unit-mongos-0: 02:35:35 ERROR juju.worker.uniter.operation hook "cluster-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-mongos-0: 02:36:21 ERROR unit.mongos/0.juju-log cluster:7: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mongos-0/charm/./src/charm.py", line 430, in <module>
    ops.main(MongosOperatorCharm)
  File "/var/lib/juju/agents/unit-mongos-0/charm/venv/ops/main.py", line 451, in __call__
    return main(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-mongos-0/charm/venv/ops/main.py", line 434, in main
    framework.reemit()
  File "/var/lib/juju/agents/unit-mongos-0/charm/venv/ops/framework.py", line 863, in reemit
    self._reemit()
  File "/var/lib/juju/agents/unit-mongos-0/charm/venv/ops/framework.py", line 942, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mongos-0/charm/lib/charms/mongodb/v0/config_server_interface.py", line 225, in _on_relation_changed
    self.charm.restart_mongos_service()
  File "/var/lib/juju/agents/unit-mongos-0/charm/./src/charm.py", line 231, in restart_mongos_service
    self.stop_mongos_service()
  File "/var/lib/juju/agents/unit-mongos-0/charm/./src/charm.py", line 222, in stop_mongos_service
    mongodb_snap = snap_cache["charmed-mongodb"]
  File "/var/lib/juju/agents/unit-mongos-0/charm/lib/charms/operator_libs_linux/v1/snap.py", line 795, in __getitem__
    self._snap_map[snap_name] = self._load_info(snap_name)
  File "/var/lib/juju/agents/unit-mongos-0/charm/lib/charms/operator_libs_linux/v1/snap.py", line 843, in _load_info
    info = self._snap_client.get_snap_information(name)
  File "/var/lib/juju/agents/unit-mongos-0/charm/lib/charms/operator_libs_linux/v1/snap.py", line 751, in get_snap_information
    return self._request("GET", "find", {"name": name})[0]
  File "/var/lib/juju/agents/unit-mongos-0/charm/lib/charms/operator_libs_linux/v1/snap.py", line 708, in _request
    response = self._request_raw(method, path, query, headers, data)
  File "/var/lib/juju/agents/unit-mongos-0/charm/lib/charms/operator_libs_linux/v1/snap.py", line 729, in _request_raw
    response = self.opener.open(request, timeout=self.timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/var/lib/juju/agents/unit-mongos-0/charm/lib/charms/operator_libs_linux/v1/snap.py", line 645, in http_open
    return self.do_open(_UnixSocketConnection, req, socket_path=self.socket_path)
  File "/usr/lib/python3.10/urllib/request.py", line 1352, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
TimeoutError: timed out
unit-mongos-0: 02:36:21 ERROR juju.worker.uniter.operation hook "cluster-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1

[32mINFO    [0m pytest_operator.plugin:plugin.py:991 Forgetting model main...